version: '3.3'
services:
  backend:
    build: ./backend
    depends_on:
      - mongodb
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment: 
      - MONGODB_CONNSTRING=mongodb://localhost:27017
    network_mode: "host"

  mongodb:
    image: 'mongo'
    volumes:
      - ./datadir/:/data/db
    network_mode: "host"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    network_mode: "host"